services:
  app:
    build:
      context: ..
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - redis

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=accelerator
      - POSTGRES_PASSWORD=accelerator
      - POSTGRES_DB=accelerator
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
