services:
  app:
    build:
      context: ..
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - oracle
      - redis

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=accelerator
      - POSTGRES_PASSWORD=accelerator
      - POSTGRES_DB=accelerator
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=accelerator
      - APP_USER_PASSWORD=accelerator
    volumes:
      - oracle-data:/opt/oracle/oradata
    ports:
      - "1521:1521"
      - "5500:5500"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  oracle-data:
