CREATE TABLE BUDGET_ALLOCATIONS (
    TENANT_ID NUMBER,
    DEPT_CODE VARCHAR2(10),
    FISCAL_YEAR NUMBER,
    ALLOCATED_AMT NUMBER(15,2),
    CONSTRAINT PK_BUDGET_ALLOCATIONS 
        PRIMARY KEY (TENANT_ID, DEPT_CODE, FISCAL_YEAR)
);

CREATE TABLE IT_EXPENSES (
    EXPENSE_ID VARCHAR2(36) PRIMARY KEY,
    TENANT_ID NUMBER,
    DEPT_CODE VARCHAR2(10),
    EXPENSE_DATE DATE,
    AMOUNT NUMBER(15,2),
    DESCRIPTION CLOB,
    IS_RECURRING NUMBER(1) CHECK (IS_RECURRING IN (0,1))
);